namespace OMNIToolsREADyMUC.Common.Enums
{
  public enum ModeEnum
  {
    // MBus mode - corresponds to commands in the Set Snoos Mode 0x2150
    MBUS_MODE_UNDEFINED = 0xFF,
    MBUS_MODE_DONT_LISTEN = 0x00,
    MBUS_MODE_SNOOS_NO_BROADCAST = 0x01,
    MBUS_MODE_SNOOS_DIRECT_BROADCAST = 0x02,
    MBUS_MODE_SNOOS_DIRECT_BROADCAST_VIA_REPEATER = 0x03,
    MBUS_MODE_SNOOS_DIRECT_BROADCAST_NO_REPEATER_CHANGE = 0x04,
    MBUS_MODE_MTO_MODE_C = 0x05,
    MBUS_MODE_MTO_MODE_T = 0x06,
    MBUS_MODE_OTM_MODE_C = 0x07,
    MBUS_MODE_MTO_MODE_C_US = 0x08,
    MBUS_MODE_OTM_MODE_T = 0x0A
  }
}